# Generated by Django 5.0.4 on 2024-06-19 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={},
        ),
        migrations.RemoveField(
            model_name="image",
            name="date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.task",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
