# Generated by Django 5.0.4 on 2024-06-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_image_options_remove_image_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
